<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="style.css" rel='stylesheet' type='text/css'>

    </head>
    <body>
        <h1>Cadabra, Inc</h1>
        <div id="description">products catalog</div>
        <div id="cadabra">
          <div class="list_container" @scroll="onScroll">
            <ul class="list">
              <li v-for="p in products"
                 class="list_item"
                 :key="p.id"
                 :class="{editing: currentlyEdited == p}">
                 <div class="view" v-if="p != currentlyEdited">
                   <label @dblclick="editProduct(p)">{{p.name}}</label>
                   <button class="destroy" @click="removeProduct(p)"></button>
                 </div>
                 <input class="edit" type="text" v-else v-model="p.name"
                  @blur="doneEdit(p)"
                  @keyup.enter="doneEdit(p)"
                  @keyup.esc="cancelEdit(p)">
                  <div class="description-view">{{p.description}}</div>
                </li>
            </ul>
          </div>
        </div>

        <script src="https://unpkg.com/vue@2.5.2/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.4"></script>
        <script src="App.vue"></script>
    </body>
</html>
