<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="style.css" rel='stylesheet' type='text/css'>
    </head>
    <body>

      <template id='editable-field'>
        <div class="view" v-if="!currentlyEdited">
          <label class="name" @dblclick="editProduct(product)">{{product.name}}</label>
          <button class="destroy">x</button>
        </div>
        <input class="edit" type="text" v-else v-model="product.name"
         @blur="doneEdit(product)"
         @keyup.enter="doneEdit(product)"
         @keyup.esc="cancelEdit(product)"/>
      </template>


        <div id="cadabra" @scroll="onScroll">
          <div class="toolbar">
            <ul class="sorting_tabs">
              <li class="sorting_tab"
                  v-for="method in listingMethods"
                  @click="selectOrdering(method)"
                  :class="{active: method.name == selectedOrdering}">{{method.text}}</li>
            </ul>
          </div>
          <div class="list_container">
            <ul class="product_list">
              <li v-for="p in products"
                 class="list_item"
                 :key="p.id"
                 :class="{editing: currentlyEdited == p}">
                 <editable-field :product.sync=p></editable-field>
                  <img :src=p.image_url class="product_image">
                  <div class="description-view">{{p.description}}</div>
                </li>
            </ul>
          </div>
        </div>

        <script src="https://unpkg.com/vue@2.5.2/dist/vue.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.4"></script>
        <script src="App.vue"></script>
    </body>
</html>
